### ISSUE TITLE
Add Ansible and Terraform

### ISSUE THREAD

**Issue by bharg4vi** [adityassharma-ss/DevOps#15]
hey there! I believe that adding Ansible and Terraform to this repo will greatly enhance its value and provide learners with valuable skills that are in high demand in the industry.

**Comment by adityassharma-ss** [comment]
Agree. But I haven't started up with Ansible and Terraform yet. If you want to contribute to it then you're most welcome.

**Comment by bharg4vi** [comment]
yes sure!
